class BPETokenizerSimple:
    def __init__(self):
        ...

    def train(self):
        ...
    
    def encode(self, text: str) -> list[int]:
        ...
    
    def decode(self, ids: list[int]) -> str:
        ...